### PR TITLE
nm - test pull request for nm/testBranch

### PR DESCRIPTION
**Pull request by pupupurin3**
This commit is to test pull request on new branch. Testfile.md was modified.

### CODE REVIEW

**Review by jin-noguchi — COMMENTED** [review]
Hey maybe change new branch to New branch...

**Review by Genki-Narimoto — COMMENTED** [review]
You should capitalize the "n" in new branch

**Review by jin-noguchi — APPROVED** [review]
Approved

**Review by Genki-Narimoto — APPROVED** [review]
Good job resolving

**Pull request merged**
