### PR TITLE
Test Pull Request for jn/TestBranch

### PR DESCRIPTION
**Pull request by jin-noguchi**
Hey, this file was used to test branching, pull requests, and merging. I added a message, "Jin was here".

### CODE REVIEW

**Review by pupupurin3 — COMMENTED** [review]
Maybe add space for pulling other changes.

**Review by Genki-Narimoto — CHANGES_REQUESTED** [review]
Consider removing hello, hi is already there

**Review by Genki-Narimoto — APPROVED** [review]
Good job resolving merge conflicts

**Review by pupupurin3 — APPROVED** [review]
Nice Resolving Merge Conflicts

**Pull request merged**
